name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net core
      uses: actions/checkout@v1 
      with:
        dotnet-version: 5.0

    # Install the .NET Core workload
    - name: Install Dependencies
      run:  dotnet restore ./FH/FH.sln
    - name: Build
      run: dotnet build ./FH/FH.Api/FH.Api.csproj --configuration Release --no-restore
     
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ./FH/FH.sln
